[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# Environment variables (set in Netlify dashboard)
# DATABASE_URL = "postgresql://..."
# JWT_SECRET = "your-jwt-secret-key"
# GOOGLE_DRIVE_CLIENT_ID = "your-google-drive-client-id"
# GOOGLE_DRIVE_CLIENT_SECRET = "your-google-drive-client-secret"
# GOOGLE_DRIVE_REFRESH_TOKEN = "admin-refresh-token"